### ISSUE TITLE
$tries on a chained Action is ignored

### ISSUE THREAD

**Issue by ferasWb** [spatie/laravel-queueable-action#104]
first of all, thank you for all your open source work! 

the issue is basically, that the `$tries` property on a chained Action doesn't work. here is an example.

Action 1:

```php 
<?php

namespace App\Actions;

use Illuminate\Support\Facades\Log;
use Spatie\QueueableAction\QueueableAction;

class TestAction
{
    use QueueableAction;

    public function execute()
    {
        sleep(10);

        Log::info('TestAction done');
    }
}

``` 

The chained Action:

```php
<?php

namespace App\Actions;

use Exception;
use Illuminate\Support\Facades\Log;
use Spatie\QueueableAction\QueueableAction;

class ChainedAction
{
    use QueueableAction;

    public int $tries = 3;

    public function backoff(): array
    {
        return [5, 30, 60];
    }

    public function execute()
    {
        sleep(10);
        throw new Exception('ChainedAction failed');
    }

    public function failed(): void
    {
        Log::error('ChainedAction failed with max tries');
    }
}

```

if I call the actions in a chain, the `ChainedAction` will not be attempted as defined per the  `$tries` property.

```php
$testAction = app(TestAction::class);
$chainedAction = app(ChainedAction::class);

$testAction->onQueue()
    ->execute()
    ->chain([
        new ActionJob($chainedAction),
    ]);
``` 

However, if the `ChainedAction` is called outside of a Chain the action will be retried normally

```php
$chainedAction = app(ChainedAction::class);

// the action will be retried 3 times as defined by the $tries and $backoff
$chainedAction->onQueue()->execute();
```

I did some debugging and there seems to be some issue with how the Queueable Properties are being resolved. 
`tries` is added dynamically to `ActionJob`.

https://github.com/spatie/laravel-queueable-action/blob/cc9273121c90d99623570199cc52bcf4699835bf/src/ActionJob.php#L115-L124

And if I define an initial `$tries` property it works in `ActionJob.php`

```php
public int $tries;
```

I am using:
V2.15
PHP 8.1
Laravel 10.43

Thanks again!

**Comment by TijmenWierenga** [comment]
I ran into the same issue today.

Solved it by extending `Spatie\QueueableAction\ActionJob` and declaring the property there:

```php
<?php
declare(strict_types=1);

namespace App\Actions;

class ActionJob extends \Spatie\QueueableAction\ActionJob
{
    public int $tries;
}

```

Next, configure that class to be used as the action in `config/queuableaction.php`:

```php
<?php
declare(strict_types=1);

return [
    'job_class' => \App\Actions\ActionJob::class,
];
```

Could this issue be reopened? I believe it could be fixed by adding all dynamically declared properties to `\Spatie\QueueableAction\ActionJob`. I'm willing to submit a PR for that.
