### ISSUE TITLE
Problem when serializing a model with binary data

### ISSUE THREAD

**Issue by heikokrebs** [spatie/laravel-queueable-action#16]
Hello!

First of all: Thanks for the practical package and the great work!

I have a problem that I couldn't solve myself so far.
I have several models that have binary data (performant UUIDs).

If I want to push an ActionJob onto the queue, that has such a model as a parameter, the serialization doesn't work correctly. All models stored in the ActionJob in `$parameters` will not be serialized as expected with the toArray() function of the models and so it comes to an error `Unable to JSON encode payload. Error code: 5`

Maybe you have a clue or some help for me?
Thanks a lot!

**Comment by nathanheffley** [comment]
Are you able to serialize binary data in a regular Laravel job? I don't think this library does any of the serialization itself and just defers to Laravel's serialization. If you have an issue with it, the problem may lie in the https://github.com/laravel/framework repository.

**Comment by heikokrebs** [comment]
> Are you able to serialize binary data in a regular Laravel job? I don't think this library does any of the serialization itself and just defers to Laravel's serialization. If you have an issue with it, the problem may lie in the [laravel/framework](https://github.com/laravel/framework) repository.

Yes i do. The normal model serialization works fine, the binary data has a text presentation for the serialization or is excluded from the `toArray()` function via the `$hidden` parameter in the model.
Thats also the workaround: build an extra job where i put this models into and use the action there. But would be even nicer to use the queueable-function of the actions directly.
