### ISSUE TITLE
Add ability to specify namespace on artisan make:action command

### ISSUE THREAD

**Issue by rmezhuev** [spatie/laravel-queueable-action#18]
Thank you for useful package. Currently actions can be generated using artisan under App\Actions only. Can you add namespace support for `name` parameter in artisan command in order to allow create actions in custom sub-folders.

**Comment by larsjanssen6** [comment]
@rmezhuev that's not an issue :)

**Comment by freekmurze** [comment]
@rmezhuev feel free to submit a PR.
