### ISSUE TITLE
Determine if execute() was called from queue or not

### ISSUE THREAD

**Issue by chelout** [spatie/laravel-queueable-action#21]
Hello!

I've got case with executing some extra code, when action is called from queue:

```php
if ($shouldBequeued) {
    // In this case i'd like to send some notifications to front in order to show end user status of execution
    $action->onQueue()->execute();
} else {
    $action->execute();
}
```

Is there any opportunity to determine if my action is run from queue? If not, maybe any hint? 🙄

Thanks in advance

**Comment by larsjanssen6** [comment]
@chelout check this out https://laravel.com/docs/5.8/events#queued-event-listeners
