### ISSUE TITLE
Add laravel common make() method to an abstract action

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-queueable-action#22]
It would be great to have a Laravel common `make()` method. Right now I've my own abstract base action but I think that this could also fit in this package.

```php
abstract class AbstractAction
{
    public static function make(array $parameters = []): self
    {
        return app(static::class, $parameters);
    }
}
```

What do you think? If you agree I'm happy to draft a PR.

**Comment by AlexVanderbist** [comment]
Hey Tom, what would the advantage be over using array destructuring?
```php
(new SomeAction(...$parameters))->execute()
// vs 
SomeAction::make($parameters)->execute()
```

**Comment by Gummibeer** [comment]
It saves the braces and `new` so it enables direct chaining. It makes the actions more Laravel like because the `make` method is everywhere.
It's more a sugar change than a real functionality.
