### ISSUE TITLE
Add support for failed method

### ISSUE THREAD

**Issue by mabalashov** [spatie/laravel-queueable-action#28]
Laravel's jobs support method `failed`. It is a very convenient way to process failed jobs.
It will be great to add support for this method

And there is no way to replace `ActionJob` in `QueueableAction`. So I cannot use my realization of `ActionJob` with `failed` method without overwriting `QueueableAction`

**Comment by stancl** [comment]
@freekmurze Would you be interested in this feature? I'd be up to implement it.

Our use case is that we send a message to Flare when the action fails.

**Comment by freekmurze** [comment]
We'll continue this in #29

**Comment by brendt** [comment]
Fixed with https://github.com/spatie/laravel-queueable-action/releases/tag/2.6.0
