### ISSUE TITLE
Change the exception argument of `failed` callback to `Throwable` interface

### ISSUE THREAD

**Issue by detygon** [spatie/laravel-queueable-action#32]
Currently is impossible (or maybe I'm not doing it properly) to throw a custom exception from a Queuable action since it requires `Exception` as argument of the `failed` callback. I think it can easily be changed to `Throwable` without breaking anything while allowing more flexibility.

**Comment by freekmurze** [comment]
Feel free to submit a PR for this. All tests should pass.
