### ISSUE TITLE
Tags aren't working on chaining

### ISSUE THREAD

**Issue by francoism90** [spatie/laravel-queueable-action#34]
The tags method isn't called when chaining, only the first one.

**Comment by nathanheffley** [comment]
I feel like I may have had a similar issue that I was able to resolve on my own. Could you post the code for your actions and how you're chaining them? It's going to be impossible to help you without a sample.

**Comment by francoism90** [comment]
@nathanheffley I just chain them as seen in the README:
```
use Spatie\QueueableAction\ActionJob;

$args = [$model];

app(MyAction::class) // does have defined tags
    ->onQueue()
    ->execute(...$args)
    ->chain([
        new ActionJob(AnotherAction::class, $args), // has no tags of the action
        new ActionJob(AnotherAction::class, $args), // has no tags of the action
    ]);
```

Like my also reported #33 issue, it seems some values aren't parsed correctly/at all. I've switched back to jobs as they work fine.
