### ISSUE TITLE
Actions invocation style

### ISSUE THREAD

**Issue by devmsh** [spatie/laravel-queueable-action#39]
While actions are very powerful, the current invocation style is quite messy, and out of the laravel coding style.

```php
// nested of this
$myInvokeableAction->onQueue()->execute($model, $requestData);

// why not to
MyInvokeableAction::execute($model, $requestData)->onQueue();
```

Just like we dispatch jobs in laravel? it is related to the IDE auto completion or there is another benefit?

**Comment by mauriciovillam** [comment]
Maybe a global helper, execute/action().

**Comment by brendt** [comment]
> it is related to the IDE auto completion

That's right. Feel free to provide your own helpers but I doubt we'll add them in this package.

**Comment by mauriciovillam** [comment]
> > it is related to the IDE auto completion
> 
> That's right. Feel free to provide your own helpers but I doubt we'll add them in this package.

Curious, why is IDE auto completion an issue here and not in one of other Spatie's packages, like [laravel-fractal](https://github.com/spatie/laravel-fractal)? It has a facade and a global helper (for example, Fractal::collection() or fractal()).

**Comment by brendt** [comment]
Laravel fractal is a very old package of ours. Our projects and team have grown significantly over the years and so has the need for proper static analysis.

**Comment by mauriciovillam** [comment]
> Laravel fractal is a very old package of ours. Our projects and team have grown significantly over the years and so has the need for proper static analysis.

Neat, I'm intrigued to know if there is any blog post or some discussion about this I can read to know more about this particular issue within Spatie's packages or Laravel in general.

**Comment by brendt** [comment]
I've written a general post about it two years ago: https://stitcher.io/blog/tests-and-types
