### ISSUE TITLE
Error in Package Discover

### ISSUE THREAD

**Issue by mustorze** [spatie/laravel-queueable-action#4]
Hi, first of all i appreciate all your packages, thank you for all

Then, after installing the this package, i`ve got a error
![capturar](https://user-images.githubusercontent.com/9161046/53129583-b7413e80-3546-11e9-8dd0-a652855a2c7e.PNG)

seeing the composer.json and searching for `providers`, you cannot find this mentioned class, but in the first release `0.0.1` the composer as diferent than master branch and had this class in `providers`, then getting this error.

**Comment by freekmurze** [comment]
I tagged a new release that fixes the problem. You might want to hold off until we release our first major version though.
