### ISSUE TITLE
Normal QueueableAction class vs Trait

### ISSUE THREAD

**Issue by Algeneralo** [spatie/laravel-queueable-action#43]
Since the current implementation doesn't support IDE autocomplete and other things, why not implementing the QueueableAction as a class instead of a trait, and it could be extended when the action is needed to be queueable.
Example:

```php
class GeneralAction extends QueueableAction
{
    public function __invoke()
    {
         //do something
    }
}
```

I'm open to doing the PR for those changes if the idea is welcomed

**Comment by Algeneralo** [comment]
ping @brendt

**Comment by brendt** [comment]
On what doesn't it support IDE autocompletion?
