### ISSUE TITLE
Allow extending the `ActionJob` class or use a custom one via configuration

### ISSUE THREAD

**Issue by detygon** [spatie/laravel-queueable-action#45]
It would be super useful to allow using a custom `ActionJob` class via configuration. Something like this:

```php
return [
    'model' => \Spatie\QueueableAction\ActionJob::class
];
```
I have a use case where I need to track the status of my jobs (progression, etc). I'm trying to use a package called [Laravel Job Status](https://github.com/imTigger/laravel-job-status) which requires me to add a trait to the dispatched jobs. I still have not found a clean way to do that. So it will be a great help to have control over the `ActionJob` class.

I can submit a PR for this feature.

**Comment by brendt** [comment]
Sounds like a good idea, feel free to submit a tested PR 👍
