### ISSUE TITLE
Adhere to Queueable "interface"

### ISSUE THREAD

**Issue by pactode** [spatie/laravel-queueable-action#5]
It would be nice if the `onQueue` method accepts the queue it should be dispatched to, just like `Illuminate\Bus\Queueable`.

Then one could use the package like this:
`$notifyUsersActions->onQueue('emails')->execute();`

Let me know your thoughts and I'll whip up a PR.

**Comment by freekmurze** [comment]
That would be a breaking change, because we already accept a `bool` there: https://github.com/spatie/laravel-queueable-action/blob/031b8d2e8d2b44de1c0d2a4eeb6b021ac350dd63/src/QueueableAction.php#L10

I'll consider this change when creating a new major version.

**Comment by Gummibeer** [comment]
Second this and I believe that it's worth an immediate breaking release.
I see no point to have a bool because if you don't want to queue it you can call `execute()` directly.

**Comment by brendt** [comment]
We also already discussed this at the office, I believe @rubenvanassche was already planning to look into it. I'm fine with tagging a major release, Ruben do you want to send a PR?

**Comment by brendt** [comment]
@pactode if you're up for sending a PR, that's also fine.

**Comment by Gummibeer** [comment]
@brendt because I have need of it I can do it!?

**Comment by brendt** [comment]
Go for it 👍

**Comment by Gummibeer** [comment]
@brendt close it again. I'm blind and dumb ...
https://github.com/Gummibeer/laravel-queueable-action/blob/ce417299dc1399556c342168ece581df19aead8e/src/QueueableAction.php#L10

https://github.com/Gummibeer/laravel-queueable-action/blob/ce417299dc1399556c342168ece581df19aead8e/tests/QueueableActionTest.php#L52-L62

**Comment by brendt** [comment]
Lol I completely missed this too 😅 Guess this was around the time I went on holiday. Problem solved 👏
