### ISSUE TITLE
Passing execute parameters to middleware method

### ISSUE THREAD

**Issue by DanielGSoftware** [spatie/laravel-queueable-action#54]
I currently have an action where im setting up middleware. The middleware requires a parameter, but currently it's not possible to achieve this. Using laravel jobs, it is possible because the parameters you pass are put in the constructor, whereas actions use the execute method. When trying to achieve the same using actions, it's not possible. You don't have access to the model.

This wont work
```php
public function execute($model)
{
    // Model is available here
}

public function middleware(): array
{
    // Cannot access the model here
    return [(new WithoutOverlapping($this->model->id))];
}
```

Proposed solution:
If we pass the same parameters for execute to the middleware, we will have access to them. [We can do that here](https://github.com/spatie/laravel-queueable-action/blob/master/src/ActionJob.php#L42-L53).

Making it like this
```php
if (is_object($action))
{
    $this->tags = $action->tags(...$parameters);
    $this->middleware = $action->middleware(...$parameters);
    if (method_exists($action, 'backoff')) {
        $this->backoff = $action->backoff(...$parameters);
    }
    if (method_exists($action, 'failed')) {
        $this->onFailCallback = [$action, 'failed'];
    }
}
```

Now we have access to the parameter like this:
```php
public function middleware(Model $model): array
{
    return [(new WithoutOverlapping($model->id))];
}
```

If we do this, we also have to delete [these lines](https://github.com/spatie/laravel-queueable-action/blob/master/src/QueueableAction.php#L67-L70). So that will be a breaking change.

Let me know what you think. And if this is also something that you'd like, I can open a PR for it.

**Comment by brendt** [comment]
@rubenvanassche do you want to look at this next week?

**Comment by DanielGSoftware** [comment]
@brendt Hi there, any update ?

**Comment by freekmurze** [comment]
Brent is enjoying a well deserved holiday. He'll answer when he gets back 👍

**Comment by kamilkozak** [comment]
It's worth starting with the fact that WithoutOverlapping middleware doesn't work with queueable action at all
