### ISSUE TITLE
Syntax error on ver. 2.10.3 - PHP 7.3.33

### ISSUE THREAD

**Issue by ericknyoto** [spatie/laravel-queueable-action#70]
PHP Unit test failed because syntax error. I think the arrow function only available on 7.4
But the composer.json itself, have min requirement of PHP ^7.2.
I installed it on PHP 7.3

Is this a bug?

```
syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')'

  at vendor/spatie/laravel-queueable-action/src/Testing/QueueableActionFake.php:94
     90▕
     91▕     protected static function getChainedClasses()
     92▕     {
     93▕         return collect(Queue::pushedJobs()[ActionJob::class] ?? [])
  ➜  94▕             ->map(fn ($actionJob) => $actionJob['job']->chained)
     95▕             ->map(function ($chain) {
     96▕                 return collect($chain)->map(function ($job) {
     97▕                     return unserialize($job)->displayName();
     98▕                 });

```
https://github.com/spatie/laravel-queueable-action/blob/2.10.3/src/Testing/QueueableActionFake.php#L94

**Comment by freekmurze** [comment]
This package requires PHP 8: https://github.com/spatie/laravel-queueable-action/blob/574264fb36fed52d29a1a83dbe2a0a8860cf298b/composer.json#L37
