### ISSUE TITLE
Breaking change in Laravel v9.38.0 - removed methods from SerializesModels trait

### ISSUE THREAD

**Issue by dimitri-koenig** [spatie/laravel-queueable-action#86]
A fatal error occurs when dispatching jobs due to this recent change in Laravel:

https://github.com/laravel/framework/pull/44847

The ActionJob class relies on __sleep and __wakeup from \Illuminate\Queue\SerializesModels.

**Comment by dimitri-koenig** [comment]
A PR already exists: #85

**Comment by freekmurze** [comment]
Thanks for the PR.
